[workspace]
name = "ros-jazzy-motion-stack"
channels = [
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/motion-stack",
]
platforms = [
  "linux-64",
  "linux-aarch64",
]
preview = ["pixi-build"]

[dependencies]
ros-jazzy-motion-stack = { path = "." }
ros-jazzy-motion-stack-msgs = "*"
ros-jazzy-xacro = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-joint-state-publisher = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-tf2-sensor-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-builtin-interfaces = "*"
numpy = "*"
nptyping = "*"
quaternion = "*"
scipy = "*"
spatialmath-python = "*"
roboticstoolbox-python  = "*"

[package]
name = "ros-jazzy-motion-stack"
version = "1.0.0"
description = "The motion stack provides control for (multi-)limbed systems"
authors = ["Elian Neppel <neppel.elian.s6@dc.tohoku.ac.jp>"]
homepage = "https://motion-stack.deditoolbox.fr/"
license = "MIT"
repository = "https://github.com/2lian/Motion-Stack"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "jazzy"

[package.build-dependencies]
setuptools = "*"

[package.host-dependencies]
setuptools = "*"

[package.run-dependencies]
ros-jazzy-motion-stack = { path = "." }
ros-jazzy-motion-stack-msgs = "*"
ros-jazzy-xacro = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-joint-state-publisher = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-tf2-sensor-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-builtin-interfaces = "*"
numpy = "*"
nptyping = "*"
quaternion = "*"
scipy = "*"
spatialmath-python = "*"
roboticstoolbox-python  = "*"
