[workspace]
name = "motion_stack"
description = "From modular robots with distributed computation, to a simple robotic arm, the motion stack provides control for (multi-)limbed systems."
channels = [
        # "robostack-kilted", 
        "robostack-jazzy", 
        # "robostack-humble", 
        "https://prefix.dev/conda-forge", 
        "conda-forge",
    ]
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[package] 
name = "motion_stack"
version = "0.0.0"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.run-dependencies]
python = "*"
pytest = "*"
numpy = "*"
nptyping = "*"
quaternion = "*"
scipy = "*"
spatialmath-python = "*"
roboticstoolbox-python  = "*"
matplotlib = "*"
