[workspace]
name = "ros-jazzy-motion-stack-tuto"
channels = [
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/motion-stack",
]
platforms = [
  "linux-64",
  "linux-aarch64",
]
preview = ["pixi-build"]

[dependencies]
ros-jazzy-motion-stack-tuto = { path = "." }
ros-jazzy-motion-stack = "*"
ros-jazzy-ros-core = "*"
ros-jazzy-xacro = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-rclpy = "*"

[package]
name = "ros-jazzy-motion-stack-tuto"
homepage = "https://motion-stack.deditoolbox.fr/"
license = "MIT"
repository = "https://github.com/2lian/Motion-Stack"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "jazzy"

[package.build-dependencies]
setuptools = "*"

[package.host-dependencies]
setuptools = "*"

[package.run-dependencies]
ros-jazzy-motion-stack = "*"
ros-jazzy-ros-core = "*"
ros-jazzy-xacro = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-rclpy = "*"
