[workspace]
name = "ros-jazzy-motion-stack-msgs"
channels = [
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
platforms = [
  "linux-64",
  "linux-aarch64",
]
preview = ["pixi-build"]

[dependencies]
ros-jazzy-motion-stack-msgs = { path = "." }

[package]
name = "ros-jazzy-motion-stack-msgs"
version = "0.0.1"
description = "ROS messages for the Motion-Stack"
authors = ["Elian Neppel <neppel.elian.s6@dc.tohoku.ac.jp>"]
homepage = "https://motion-stack.deditoolbox.fr/"
license = "MIT"
repository = "https://github.com/2lian/Motion-Stack"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "jazzy"

