name: Tests Windows
on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        ros-version: ["humble", "jazzy", "kilted"]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.9.2
      with:
        cache: true
        environments: ${{ matrix.ros-version }}
    - name: Pixi Colcon build
      run: |
        pixi run -e ${{ matrix.ros-version }} build
    - name: Pixi Pytest
      run: |
        pixi run -e ${{ matrix.ros-version }} pytest ./src/motion_stack/test/ -s
